# Generated by Django 3.2.6 on 2021-10-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_name',
            field=models.CharField(max_length=200),
        ),
    ]
